# Generated by Django 4.0.2 on 2022-02-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
